sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

branches:
  only:
  - master

services: docker

env:
  matrix:
  #- INSTANCE=default-centos-5 #times out in travis
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-fedora-23
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-opensuse-132
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
  - script: /opt/chefdk/embedded/bin/cookstyle
    env:  COOKSTYLE=1
  - script: /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
    env:  FOODCRITIC=1
  - script: /opt/chefdk/embedded/bin/rspec
    env:  CHEFSPEC=1
