sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  matrix:
  - INSTANCE=default-centos-5
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-fedora-23
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-opensuse-132
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604

  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/cookstyle
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
